language: java
sudo: false
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk13
cache:
  directories:
    - $HOME/.m2/repository

env:
  - MAVEN_VERSION=3.6.0

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"

script:
  - "./mvnw --show-version --errors --batch-mode -Pit clean verify"
